// <auto-generated />
using System;
using LoyallaApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LoyallaApi.Migrations
{
    [DbContext(typeof(LoyallaContext))]
    partial class LoyallaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LoyallaApi.DBModels.Cases", b =>
                {
                    b.Property<int>("Case_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int?>("Created_By")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("integer");

                    b.HasKey("Case_Id");

                    b.ToTable("Case_tbl");
                });

            modelBuilder.Entity("LoyallaApi.DBModels.Feedback", b =>
                {
                    b.Property<int>("Feedback_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("Case_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Created_By")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Feedbacks")
                        .HasColumnType("text");

                    b.Property<int>("Student_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updated_By")
                        .HasColumnType("integer");

                    b.HasKey("Feedback_Id");

                    b.ToTable("Feedback_tbl");
                });

            modelBuilder.Entity("LoyallaApi.DBModels.Options", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<double>("IsAnwsers")
                        .HasColumnType("double precision");

                    b.Property<string>("OptionName")
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int?>("QuestionsQuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionsQuestionId");

                    b.ToTable("Options_tbl");
                });

            modelBuilder.Entity("LoyallaApi.DBModels.Paper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("CaseId")
                        .HasColumnType("integer");

                    b.Property<int?>("CasesCase_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("PaperName")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("correctOptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CasesCase_Id");

                    b.ToTable("Paper_tbl");
                });

            modelBuilder.Entity("LoyallaApi.DBModels.Questions", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("CorrectOptionId")
                        .HasColumnType("integer");

                    b.Property<int>("Created_By")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("PaperId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionName")
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updated_By")
                        .HasColumnType("integer");

                    b.HasKey("QuestionId");

                    b.HasIndex("PaperId");

                    b.ToTable("Question_tbl");
                });

            modelBuilder.Entity("LoyallaApi.DBModels.Signup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Age")
                        .HasColumnType("text");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Field")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("MedicalTraining")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("School")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<string>("otherField")
                        .HasColumnType("text");

                    b.Property<string>("otherStatus")
                        .HasColumnType("text");

                    b.Property<string>("otherTraining")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Signup");
                });

            modelBuilder.Entity("LoyallaApi.DBModels.StudentCaseAttemptStatus", b =>
                {
                    b.Property<int>("StudentCaseAttemptStatus_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("Case_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Created_By")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("Student_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Updated_By")
                        .HasColumnType("integer");

                    b.HasKey("StudentCaseAttemptStatus_Id");

                    b.ToTable("StudentCaseAttemptStatus_tbl");
                });

            modelBuilder.Entity("LoyallaApi.DBModels.SubmissionDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("AttemptedOptionId")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectOptionId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionsSubmissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionsSubmissionId");

                    b.ToTable("SubmissionDetails_tbl");
                });

            modelBuilder.Entity("LoyallaApi.DBModels.Submissions", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("CaseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PaperId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.HasKey("SubmissionId");

                    b.ToTable("Submission_tbl");
                });

            modelBuilder.Entity("LoyallaApi.DBModels.Options", b =>
                {
                    b.HasOne("LoyallaApi.DBModels.Questions", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionsQuestionId");
                });

            modelBuilder.Entity("LoyallaApi.DBModels.Paper", b =>
                {
                    b.HasOne("LoyallaApi.DBModels.Cases", null)
                        .WithMany("Paper")
                        .HasForeignKey("CasesCase_Id");
                });

            modelBuilder.Entity("LoyallaApi.DBModels.Questions", b =>
                {
                    b.HasOne("LoyallaApi.DBModels.Paper", "Paper")
                        .WithMany("Questions")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("LoyallaApi.DBModels.SubmissionDetails", b =>
                {
                    b.HasOne("LoyallaApi.DBModels.Submissions", null)
                        .WithMany("Submission")
                        .HasForeignKey("SubmissionsSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyallaApi.DBModels.Cases", b =>
                {
                    b.Navigation("Paper");
                });

            modelBuilder.Entity("LoyallaApi.DBModels.Paper", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LoyallaApi.DBModels.Questions", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("LoyallaApi.DBModels.Submissions", b =>
                {
                    b.Navigation("Submission");
                });
#pragma warning restore 612, 618
        }
    }
}
